version: '3'

services:
  drupal:
    image: drupal
    container_name: my-docker
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - database
    restart: always
  
  database:
    image: postgres:9.6-alpine
    container_name: my-database
    environment:
      POSTGRES_PASSWORD: mypassword
    restart: always
  
volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
